// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8MwORr3pMENdmIyeMNbIBsLCL3KQgfyk',
    appId: '1:92722751594:web:66a8a78e81e3c963ed0213',
    messagingSenderId: '92722751594',
    projectId: 'fooddeliveryapp-9f7e1',
    authDomain: 'fooddeliveryapp-9f7e1.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-9f7e1.appspot.com',
    measurementId: 'G-PL5ZJ5X90E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkZumMlJxWm1A70SoNJvY2s1H-FYYhAbY',
    appId: '1:92722751594:android:a13a40f1bc786738ed0213',
    messagingSenderId: '92722751594',
    projectId: 'fooddeliveryapp-9f7e1',
    storageBucket: 'fooddeliveryapp-9f7e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKe6GV_jtqb8DBntyFHeOSkNaRl4t_MeQ',
    appId: '1:92722751594:ios:e3cf967c5cb009bfed0213',
    messagingSenderId: '92722751594',
    projectId: 'fooddeliveryapp-9f7e1',
    storageBucket: 'fooddeliveryapp-9f7e1.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKe6GV_jtqb8DBntyFHeOSkNaRl4t_MeQ',
    appId: '1:92722751594:ios:e3cf967c5cb009bfed0213',
    messagingSenderId: '92722751594',
    projectId: 'fooddeliveryapp-9f7e1',
    storageBucket: 'fooddeliveryapp-9f7e1.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8MwORr3pMENdmIyeMNbIBsLCL3KQgfyk',
    appId: '1:92722751594:web:16be7e5aa05fc07fed0213',
    messagingSenderId: '92722751594',
    projectId: 'fooddeliveryapp-9f7e1',
    authDomain: 'fooddeliveryapp-9f7e1.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-9f7e1.appspot.com',
    measurementId: 'G-Q1YKTVP2T2',
  );
}
